Emanuel Butoi branch
raduchistest/acs-2021 pull request #13
Opened 2021-11-03 17:21 UTC by EmanuelButoiGit

added Emanuel Butoi tasks

2021-11-03 17:25 UTC, CojocaruLiviuGabriel requested changes
Please add "Reviewed by Liviu-Gabriel Cojocaru" for file emanuel-butoi-dir/emanuelbutoi.txt

2021-11-03 17:29 UTC, EmanuelButoiGit reviewed
Reviewed by Liviu-Gabriel Cojocaru

2021-11-04 16:45 UTC, popararesd requested changes
Please add 'Reviewed by Rares Popa'

2021-11-04 16:46 UTC, popararesd approved these changes

2021-11-08 17:13 UTC, closed without merging