Paulcentea branch
raduchistest/acs-2021 pull request #15
Opened 2021-11-05 18:23 UTC by CenteaPaul

added paul centea tasks

2021-11-05 18:29 UTC, ionut0 requested changes

2021-11-05 18:29 UTC, ionut0 commented on paul-centea-dir/paulcentea.txt
> +second commit
reviewed by Ionut Poplacean

2021-11-05 18:39 UTC, CenteaPaul commented on paul-centea-dir/paulcentea.txt
> +second commit
done

2021-11-05 18:45 UTC, ionut0 approved these changes

2021-11-13 15:58 UTC, FlorinCiobotea requested changes
Add "reviewed by FlorinCiobotea"

2021-11-13 16:55 UTC, FlorinCiobotea approved these changes

2021-11-13 17:23 UTC, MelittaPirjolea requested changes

2021-11-13 17:23 UTC, MelittaPirjolea commented on paul-centea-dir/paulcentea.txt
> +reveiwed by FlorinCiobotea
add reviewed by MelittaPirjolea

2021-11-13 17:36 UTC, MelittaPirjolea approved these changes

2021-11-13 17:36 UTC, merged