Iuliavasilas branch
raduchistest/acs-2021 pull request #17
Opened 2021-11-07 13:33 UTC by IuliaVasilas

Added Iulia Vasilas tasks

2021-11-07 13:55 UTC, aidaturbureanu requested changes

2021-11-07 13:55 UTC, aidaturbureanu commented on iulia-vasilas-dir/iuliavasilas.txt
> +second commit
reviewed by Aida-Maria Turbureanu

2021-11-07 16:26 UTC, IuliaVasilas commented on iulia-vasilas-dir/iuliavasilas.txt
> +second commit
done

2021-11-08 15:57 UTC, delialotrean approved these changes

2021-11-08 16:07 UTC, delialotrean requested changes
Make a change here

2021-11-08 16:15 UTC, delialotrean approved these changes
All good now

2021-11-08 16:20 UTC, aidaturbureanu approved these changes

2021-11-08 16:22 UTC, merged