Rarespopa branch
raduchistest/acs-2021 pull request #4
Opened 2021-11-01 18:23 UTC by popararesd

Added Rares Popa Tasks

2021-11-01 18:28 UTC, raduchistest requested changes

2021-11-01 18:28 UTC, raduchistest commented on rares-popa-dir/rarespopa.txt
> +second commit
Add reviewed by RaduChis

2021-11-01 18:35 UTC, popararesd commented on rares-popa-dir/rarespopa.txt
> +second commit
Done

2021-11-01 18:39 UTC, BogdanCanciuACS requested changes
Add reviewed by bogdanCanciu

2021-11-01 18:40 UTC, BogdanCanciuACS approved these changes

2021-11-04 16:42 UTC, merged

2021-11-08 16:59 UTC, BogdanBadiu commented
Please add "Reviewed by Bogdan-Vasile Badiu"