FlorinCiobotea branch
raduchistest/acs-2021 pull request #5
Opened 2021-11-01 19:21 UTC by FlorinCiobotea

added Florin Ciobotea tasks

2021-11-05 12:38 UTC, lucianignat requested changes
add "reviewed by LucianIgnat"

2021-11-05 18:49 UTC, CenteaPaul requested changes

2021-11-05 18:49 UTC, CenteaPaul commented on florin-ciobotea-dir/florinciobotea.txt
> +second commit
reviewed by paulCentea

2021-11-07 13:57 UTC, aidaturbureanu requested changes

2021-11-07 13:57 UTC, aidaturbureanu commented on florin-ciobotea-dir/florinciobotea.txt
> +second commit
reviewed by Aida-Maria Turbureanu

2021-11-13 16:40 UTC, aidaturbureanu approved these changes

2021-11-13 16:41 UTC, CenteaPaul approved these changes

2021-11-13 17:06 UTC, merged