Andreipatrausanu branch
raduchistest/acs-2021 pull request #6
Opened 2021-11-01 19:22 UTC by AndreiPatrausanu

added andrei patrausanu tasks

2021-11-01 19:36 UTC, Zackyzz requested changes

2021-11-01 19:36 UTC, Zackyzz commented on andrei-patrausanu-dir/andreipatrausanu.txt
> +second commit
Please add "reviewed by zahariaBurghelea"

2021-11-01 19:56 UTC, AndreiPatrausanu commented on andrei-patrausanu-dir/andreipatrausanu.txt
> +second commit
Done

2021-11-01 21:18 UTC, Zackyzz approved these changes

2021-11-02 15:22 UTC, BogdanCanciuACS requested changes
Add "reviewed by bogdanCanciu"

2021-11-02 15:23 UTC, BogdanCanciuACS approved these changes

2021-11-03 12:09 UTC, merged