Lucianignat branch
raduchistest/acs-2021 pull request #7
Opened 2021-11-01 19:54 UTC by lucianignat

added lucian ignat tasks

2021-11-02 20:34 UTC, CrinaCarmen approved these changes

2021-11-02 20:43 UTC, CrinaCarmen requested changes
Please add one more comment in lucianignat.txt file

2021-11-03 11:39 UTC, IuliaBirza requested changes

2021-11-03 11:39 UTC, IuliaBirza commented on lucian-ignat-dir/lucianignat.txt
> +second commit
reviewed by IuliaBirza

2021-11-05 18:49 UTC, IuliaBirza approved these changes

2021-11-08 15:49 UTC, CrinaCarmen approved these changes

2021-11-08 18:52 UTC, merged