Liviugabrielcojocaru branch
raduchistest/acs-2021 pull request #8
Opened 2021-11-02 07:02 UTC by CojocaruLiviuGabriel

added firstname lastname tasks

2021-11-02 07:08 UTC, popararesd requested changes
Please add 'Reviewed by Rares Popa'.

2021-11-03 11:31 UTC, IuliaBirza requested changes

2021-11-03 11:31 UTC, IuliaBirza commented on liviu-gabriel-cojocaru-dir/liviugabrielcojocaru.txt
> +second commit
reviewed by IuliaBirza

2021-11-03 14:39 UTC, popararesd approved these changes

2021-11-03 14:53 UTC, IuliaBirza approved these changes

2021-11-03 14:56 UTC, merged

2021-11-08 16:58 UTC, BogdanBadiu commented
Please add "Reviewed by Bogdan-Vasile Badiu"